image: ruby:2.6.5

before_script:
  - ruby -v
  - gem install bundler -v 2.3.12
  - bundle install

standard:
  script:
    - bundle exec rake

ruby-2.7:
  image: ruby:2.7
  script:
    - bundle exec rake

ruby-3.0:
  image: ruby:3.0
  script:
    - bundle exec rake

ruby-3.1:
  image: ruby:3.1
  script:
    - bundle exec rake